ВЕКТОРЫ

In [2]:
import numpy as np
v = np.array([1,5,4,6,8])
print(f'третья компомента вектора v: {v[2]}')
print(f'размерность v: {len(v)}')

третья компомента вектора v: 4
размерность v: 5


In [3]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
a + b

array([15, 23, 14,  8])

In [4]:
a - b

array([ 5, -7, -4, -6])

In [5]:
0.2*a

array([2. , 1.6, 1. , 0.2])

In [6]:
#Задание 2.5
#Ниже представлены доходы семьи за три месяца.

#Доходы мужа: 120, 150 и 190 тысяч рублей.
#Доходы жены: 130, 130 и 130 тысяч рублей.
#Доходы тёщи: 2, 3 и 2.5 тысячи евро.
#Вводите координаты полученных векторов через запятую (без пробела). Пример ввода ответа: 0,1,1.

#Найдите вектор доходов тёщи в тыс. рублей, если курс евро составляет 72 рубля.

In [7]:
m = np.array([120, 150, 190])
z = np.array([130, 130, 130])
t = np.array([2,3,2.5])
kurs = 72
print(t*72)

[144. 216. 180.]


In [8]:
m+z+t*72

array([394., 496., 500.])

In [9]:
#Задание 2.6
#Найдите длину диагонали параллелограмма (сумму векторов), построенного на векторах
a = np.array([4,6])
b = np.array([-1,-2])
v = a+b
np.sqrt(v[0]**2+v[1]**2)

5.0

In [10]:
#2.8
p = np.array([3,4,5,9])
s = np.array([1,5,3,6])
s*400-p*200

array([-200, 1200,  200,  600])

In [11]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)

102.0

In [12]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [13]:
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [14]:
#Задание 3.3
#Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). 
#Для преобразования DataFrame в массив numpy можно воспользоваться атрибутом values:
v = Hut_Paradise_DF.values[4]
v

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [15]:
#Задание 3.4
#Найдите вектор этажей всех квартир. Выберите координаты полученного вектора:
v = Hut_Paradise_DF.values[:,3]
v

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [16]:
#Задание 3.5
#Вычислите вектор нежилой площади. Выберите координаты полученного вектора:
Hut_Paradise_DF.values[:,1] - Hut_Paradise_DF.values[:,5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [17]:
#Задание 3.6
#Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, 
# в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, 
# в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

#Найдите продолжительность просмотров в минутах во всех квартирах за две недели.
p = np.array([10,20,30,15,5,40,20,8,20])
v = Hut_Paradise_DF.values[:,4]
(p*v).sum()

1348

In [18]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [19]:
#Задание 3.7
#Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3. Выберите координаты полученного вектора

v*2+w*-3

array([-3, 14,  3,  4,  2])

In [20]:
#Задание 3.8
#Будет ли эта комбинация ортогональна вектору  u?

u @ (v*2+w*-3)

0

МАТРИЦЫ

In [21]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [22]:
A = np.matrix([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

matrix([[ 1, -5,  3],
        [ 2,  2,  1],
        [ 0,  3,  1],
        [ 2,  4, 12]])

In [23]:
display(A.shape)
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])



(4, 3)

a_23= 1 a_32= 3 a_33= 1


In [24]:

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [25]:
#Задание 5.1
#Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.
#В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

Inc = np.array([Husband_Income,Wife_Income,Mother_In_Law_Income])
Inc = Inc.T
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [26]:
#Задание 5.2
#Составьте матрицу Con расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.
#В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.
Con = np.array([Husband_Consumption,Wife_Consumption,Mother_In_Law_Consumption]).T
Con

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [27]:
#Задание 5.3
#Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.
#Используйте полученную ранее матрицу Inc, где доходы расположены по столбцам.

Inc*(1-0.13)

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [28]:
#Задание 5.4
#Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц 
# (то есть разницу между доходами после вычета налога и расходами).

Inc*(1-0.13) - Con

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

УМНОЖЕНИЕ МАТРИЦ

In [29]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [30]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [31]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [32]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [33]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

In [34]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [35]:
#Задание 7.1
#Найдите произведение матрицы A и вектора х
# в том порядке, в котором их можно умножить.

#В качестве ответа запишите координаты получившегося вектора через запятую, без пробелов. Пример ввода ответа: 1,1.
A@x

array([26, 30])

In [36]:
#Задание 7.2
#Даны две матрицы:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
#Найдите произведение матриц  и  в том порядке, в котором их можно умножить.
#В качестве ответа через запятую, без пробелов запишите элемент чётвертого столбца первой строки.
print(A.shape)
print(B.shape)

(5, 4)
(2, 5)


In [37]:
(B@A)[0,3]

14

In [38]:
#Задание 7.3
#Дана система векторов:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
#Составьте матрицу A, расположив векторы x, y,z  в строках. Найдите матрицу Грама G 
# (матрицу скалярных произведений столбцов матрицы ) системы векторов x,y ,z .
#Чему равна полученная матрица Грама ?
A = np.array([x,y,z])
A.T@A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [39]:
#УСЛОВИЕ ДЛЯ ЗАДАНИЙ 7.4 И 7.5
#В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 
#Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

#В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
#В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [40]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [41]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [42]:
#Задание 7.4
#Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят салону определённую комиссию.
#Вектор комиссий: com = np.array([0.2, 0.2, 0.3, 0.1, 0.1]).
A = Count_DF.values * Price_DF.values #Смотрим сколько денег принес каждый стилист по каждой услуге
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1]) #Комиссии салона
A@com


array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [43]:
#Задание 7.5
#Найдите вектор прибыли стилистов.
#Выберите координаты полученного вектора:
slylists = np.ones(5) - com
A@slylists

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

Обратная матрица. Определитель матрицы

In [44]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [45]:
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [47]:
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))


-2.9999999999999996


РАНГ

In [48]:

v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

2


In [50]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,10,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))

3


In [51]:
#Задание 10.1
#Дана матрица :
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
#Найдите матрицу, обратную матрице .
#В качестве ответа запишите элемент из первого столбца второй строки, округлив его до трёх знаков после точки-разделителя.

In [53]:
np.linalg.inv(A)[1,0]

0.3750000000000005

In [54]:
#УСЛОВИЕ ДЛЯ ЗАДАНИЙ 10.2-10.7

#Дана система векторов:

v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [57]:
#Задание 10.2
#Найдите ранг системы векторов v1, v2, v3, v4. Для этого создайте матрицу системы векторов. Векторы в матрице расположите в столбцы.
A = np.array([v1,v2,v3,v4]).T
np.linalg.matrix_rank(A)

4

In [60]:
A

array([[ 9,  2,  4,  3],
       [10,  0,  0, -4],
       [ 7,  5,  0,  3],
       [ 7,  1,  4, -1],
       [ 9,  4,  1, -4]])

In [67]:
#Задание 10.4
#Найдите матрицу Грама системы векторов v1, v2, v3, v4: . В качестве ответа запишите элемент из четвёртого столбца первой строки.
(A.T@A)[0,3]


-35

In [69]:
round(np.linalg.det(A.T@A),0)

3716648.0

In [ ]:
#Задание 10.7
#Найдите обратную матрицу к матрице Грама  системы.
#В качестве ответа запишите элемент из первого столбца третьей строки, округлив его до трёх знаков после точки-разделителя.

In [71]:
G = A.T@A
round(np.linalg.inv(G)[2,0],3)

-0.026