In [1]:
# Основы
x = 5
y = 5.5
z = [1,2,3,4]
t = {1:'a', 2:'b', 3:'c'}
u = (1,2,'a','b')
v = {1,'s','a',3}

var_list = [x,y,z,t,u,v]

type_list = map(type, var_list) # type - выводит тип переменной
id_list = list(map(id, var_list)) # id - уникальный идентификатор объекта. По сути, что это за объект в памяти


print(f'Напечатаем сами переменные: {x,y,z,t,u,v}')
print(f'Выведем типы переменных: {list(type_list)}')
print(f'Выведем идентификаторы переменных: {id_list}')

x1 = x
print(id(x1),id(x)) #разными переменными назван один объект. Видим это с помощью id

#Операции
print(7**5) # ** - возведение в степень
print(7/5) # / - деление
print(7//5) # // - целочисленное деление
print(7%5) # / - остаток от деления
print(round(7/3,3)) # округение round(число, кол-во знаков после запятой=0)

Напечатаем сами переменные: (5, 5.5, [1, 2, 3, 4], {1: 'a', 2: 'b', 3: 'c'}, (1, 2, 'a', 'b'), {1, 3, 's', 'a'})
Выведем типы переменных: [<class 'int'>, <class 'float'>, <class 'list'>, <class 'dict'>, <class 'tuple'>, <class 'set'>]
Выведем идентификаторы переменных: [1723422108080, 1723505923824, 1723505928192, 1723507022528, 1723506454096, 1723506559680]
1723422108080 1723422108080
16807
1.4
1
2
2.333


In [2]:
#Работа со строками

s = 'Hello!'
print(s[:2],s[1:3],s[:-2],s[3:],s[-2:],s[::2]) #Работа со срезами [первый : последний : шаг]
print('Hel' + 'lllllo!') #конкатенация
print('lol'*5) #умножение строки на число
print(len(s)) # len() - длина строки
print(s.find('lo')) # посик подстроки в строке (метод)
print(s.upper())
print(s.lower())
print(s.isalpha()) #только ли буквы
print(s.isdigit()) #только ли цифры
print(s.isalnum()) #только ли буквы и цифры
 
# раделение строки по разделетелю split
s1 = 'a string for split'
s2 = 'a,string,for, ,split'
print(s1.split())
print(s2.split(','))

#склеить строки с разделителем 'разделитель'.join(список)
str_list = s1.split()
s2 = ' ! ! '
print(s2.join(str_list))

He el Hell lo! o! Hlo
Hellllllo!
lollollollollol
6
3
HELLO!
hello!
False
False
False
['a', 'string', 'for', 'split']
['a', 'string', 'for', ' ', 'split']
a ! ! string ! ! for ! ! split


In [3]:
#Форматирование вывода строк
#f-строка
print(f'f-СТОКА:\n Мы берем и вставляем переменные прям сюда. Например строка s = {s}, \nА вот список: {s2.join(str_list)}, \nА еще вот число: {round(7/3,5)}')

#а можно еще через метод format
print('\nformat()\nМы берем и вставляем переменные прям сюда. Например строка s = {}, \nА вот список: {}, \nА еще вот число: {}'.format(s, s2.join(str_list), round(7/3,5)))

f-СТОКА:
 Мы берем и вставляем переменные прям сюда. Например строка s = Hello!, 
А вот список: a ! ! string ! ! for ! ! split, 
А еще вот число: 2.33333

format()
Мы берем и вставляем переменные прям сюда. Например строка s = Hello!, 
А вот список: a ! ! string ! ! for ! ! split, 
А еще вот число: 2.33333


In [4]:
#Работа со списками
#СОЗДАНИЕ СПИСКОВ
print('\nСОЗДАНИЕ СПИСКОВ')
print([])
print(list())
print([1,2,3,4,5])
print(['as','df','gh','jk'])
print(list(range(10)))
print(list(range(10,20)))
print(list(range(10,20,3)))
print([list(range(10)),'в списке бывают разные объекты',list(range(10,20,3))]) # в спсике бывают разные объекты

#СРЕЗЫ СПИСКОВ
print('\nСРЕЗЫ')
lst = list(range(100))
print(lst[::5])
print(lst[:10:2])
print(lst[-10::3])
print(lst[::-5])

#МЕТОДЫ СПИСКОВ
print('\nМЕТОДЫ ТИПА СПИСОК')
lst = list(range(10))
print(lst)

lst.append('добавили в список') #методы append изменяет объект который его вызывает
print(lst.count(3)) #count считаем число элементов равных данному в списке

lst2 = lst.copy() #копируем список в новый объект с новым id

lst.extend(lst2[::-1]) #добавляем в список элементы другого списка в обратном порядке
print(lst)

lst = list(range(10,0,-1))
print(lst)
lst.pop() #eудалить элемент списка
lst.pop(3) #удалить элемент с номером
print(lst)
lst.sort() #сортировка
print(lst)
lst.clear() #очистка
print(lst)


СОЗДАНИЕ СПИСКОВ
[]
[]
[1, 2, 3, 4, 5]
['as', 'df', 'gh', 'jk']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[10, 13, 16, 19]
[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 'в списке бывают разные объекты', [10, 13, 16, 19]]

СРЕЗЫ
[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]
[0, 2, 4, 6, 8]
[90, 93, 96, 99]
[99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19, 14, 9, 4]

МЕТОДЫ ТИПА СПИСОК
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
1
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'добавили в список', 'добавили в список', 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[10, 9, 8, 6, 5, 4, 3, 2]
[2, 3, 4, 5, 6, 8, 9, 10]
[]


In [5]:
# КОРТЕЖИ - неизменяемые братья списков
t = tuple()
print(t)
t = ('a',1,5,list(range(4)))
print(t)

()
('a', 1, 5, [0, 1, 2, 3])


In [6]:
# СЛОВАРИ
dict1 = dict()
dict2 = {'name':'John', (2,7):6, 3.5:[5,8,5]}
print(dict1,'\n',dict2)
print(dict2.keys())
print(set(dict2.keys())) #взять ключи
print(dict2.values())
print(list(dict2.values())) #взять значения

#работа со словарями
print('работа со словарями')
print(dict2['name'])
print(dict2.get('name'))
dict2.update({'name2':'Mike','name3':'Helga'}) #Добавить словарь в словарь
print(dict2)
dict2.pop('name2') #удалить элемент по ключу
print(dict2)
dict2.setdefault('surname','Nikolaev') #добавление
print(dict2)
#А можно просто вот так добавить
dict2['new key'] = 'new value'
print(dict2)

{} 
 {'name': 'John', (2, 7): 6, 3.5: [5, 8, 5]}
dict_keys(['name', (2, 7), 3.5])
{'name', 3.5, (2, 7)}
dict_values(['John', 6, [5, 8, 5]])
['John', 6, [5, 8, 5]]
работа со словарями
John
John
{'name': 'John', (2, 7): 6, 3.5: [5, 8, 5], 'name2': 'Mike', 'name3': 'Helga'}
{'name': 'John', (2, 7): 6, 3.5: [5, 8, 5], 'name3': 'Helga'}
{'name': 'John', (2, 7): 6, 3.5: [5, 8, 5], 'name3': 'Helga', 'surname': 'Nikolaev'}
{'name': 'John', (2, 7): 6, 3.5: [5, 8, 5], 'name3': 'Helga', 'surname': 'Nikolaev', 'new key': 'new value'}


In [7]:
#МНОЖЕСТВА
s = set(range(10))
print(s)
s.add('a') #добавить элемент
print(s)
s.remove('a') #удалить элемент
s.discard(0) #удалить еще элемент
print(s)
#объединение
s=s.union(set(range(5,15)))
print(s)
s=s.intersection(set(range(3,20))) #пересечение
print(s)
s=s.difference(set(range(10,20))) #разность
print(s)
print(s.issubset(set(range(5,7)))) #проверка на подмножество
print(set(range(5,7)).issubset(s)) #проверка на подмножество

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'a'}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14}
{3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14}
{3, 4, 5, 6, 7, 8, 9}
False
True


In [8]:
# условные операторы
x = 2
if x/2 == 0.5:
    print(f"== works {x/2}")
elif x/3 > 1.3:
    print(f'!!! {x/3}')
else:
    print(f'wow {x}')
    
#инлайновый
y = 2 if x != 2 else 3
print(y)


wow 2
3


In [9]:
#цикл for
# for value in iterator - бегаем по итерируемуму объекту
for i in range(10):
    print(i)
print('\nwhile')
i = 0
while i<10:
    i+=2
    print(i)
print('\nwhile True')
while True:
    i+=2
    print(i)
    if i>20:
        break

0
1
2
3
4
5
6
7
8
9

while
2
4
6
8
10

while True
12
14
16
18
20
22


In [10]:
# функции

def new_f(x):
    return x**x

print(new_f(5))

def new_f(speed=0):
    if speed<0:
        raise ValueError('Speed must be >0')
    return speed ** (1/2)

print(new_f(3))
print(new_f(-3))

3125
1.7320508075688772


ValueError: Speed must be >0

In [ ]:
def root(x, n=2):
    return x**(1/n)

print(root(4))
print(root(4,3))
print(root(4, n=6))

# def function(*args, **kwargs) #получение переменного числааргементов и переменных. Порядковые первые передаются
new_list = list(range(1,10,2))
how = {'sep':', ', 'end':' !!!'}
print(*new_list, **how)

def f(*args, **kwargs):
    print(args)
    print(kwargs)

print('\n')
f(*new_list, **how)

2.0
1.5874010519681994
1.2599210498948732
1, 3, 5, 7, 9 !!!

(1, 3, 5, 7, 9)
{'sep': ', ', 'end': ' !!!'}


In [ ]:
# lambda
get_len = lambda x: len(x)
print(get_len('asdfgh'))

mult = lambda x,y: x*y
print(mult(2,4))


#Сортировка по нескольким параметрам
lst = ['a','b','cc','dd','aaa','bbbb','e']
lst.sort(key = lambda x: (x, len(x))) #сначала алфавит, а потом длина
print(lst)

6
8
['a', 'aaa', 'b', 'bbbb', 'cc', 'dd', 'e']


In [ ]:
# ИТЕРАТОРЫ
my_list = list(range(1,30,3))
iter_list = iter(my_list)
elem = next(iter_list)
print(elem)
elem = next(iter_list)
print(elem)
elem = next(iter_list)
print(elem)

for el in iter_list:
    print(el, el*el)

my_list = list(range(1,30,3))
iter_list = iter(my_list)
new_list = list(iter_list)
print(new_list) #выдаем в список все оставшиеся объекты итератора

1
4
7
10 100
13 169
16 256
19 361
22 484
25 625
28 784
[1, 4, 7, 10, 13, 16, 19, 22, 25, 28]


In [ ]:
#ГЕНЕРАТОРЫ
def gen(num):
    for i in range(1,num+1):
        yield i**i
# теперь мы сгенерировали итератор, который выдает квадраты в диапазоне от 1 до num вкл

new_gen = gen(6)
elem = next(new_gen)
print(elem)
elem = next(new_gen)
print(elem)
elem = next(new_gen)
print(elem)

for i in new_gen:
    print(i)


1
4
27
256
3125
46656


In [ ]:
# СОКРАЩЕНИЯ
# генератор в строку:
gen = (x**x for x in range(1,7))
for i in gen:
    print(i)
    
# создадим список формулой
gen_list = [x**x for x in range(1,9)]
print(gen_list)

# создадим множество формулой
set_list = {x**3 for x in range(1,9)}
print(set_list)

# создадим множество формулой
tuple_list = tuple(x**5 for x in range(1,9))
print(tuple_list)

#и добавим еще условие
gen_list = [x**2 for x in range(1,19) if x%2 == 0]
print(gen_list)

# а можно и словарь создать
dct = {key : key**2 for key in range(1,10)}
print(dct)
dct = {key : val for key,val in enumerate(range(1,10))}
print(dct)

1
4
27
256
3125
46656
[1, 4, 27, 256, 3125, 46656, 823543, 16777216]
{64, 1, 512, 8, 343, 216, 27, 125}
(1, 32, 243, 1024, 3125, 7776, 16807, 32768)
[4, 16, 36, 64, 100, 144, 196, 256, 324]
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9}


In [ ]:
#функции для итераторов
it = range(10) #range - это итерируемый объект
print(list(it))

#map
mp = map(lambda x: 1 if x%3 else 2, it) #map(f, it) применяет функцию f к итерируемуму объекту it, получая итерируемый объект типа map
print(list(mp))

#filter
fl = filter(lambda x: True if x >= 5 else False, it) #filter(f, it), только f булевы значения должны возвращать, когдые передадульсы в отфильтрованный итератор типа filter
print(list(fl))

#zip - пакует итераторы, чтобы по ним одновременно идти
it = range(10)
lst = []
for i in it:
    lst.append('letter' + str(i))

for i, l in zip(it, lst):
    print(i, l)
    
#enumerate - нумерует итератор
print(list(enumerate(lst)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 1, 1, 2, 1, 1, 2, 1, 1, 2]
[5, 6, 7, 8, 9]
0 letter0
1 letter1
2 letter2
3 letter3
4 letter4
5 letter5
6 letter6
7 letter7
8 letter8
9 letter9
[(0, 'letter0'), (1, 'letter1'), (2, 'letter2'), (3, 'letter3'), (4, 'letter4'), (5, 'letter5'), (6, 'letter6'), (7, 'letter7'), (8, 'letter8'), (9, 'letter9')]


In [ ]:
def star_triangle(r):
   for x in range(r):
      print(' '*(r-x-1)+'*'*(2*x+1))

star_triangle(3)

  *
 ***
*****


In [ ]:
#deque
from collections import deque

d = deque(list(range(6)),maxlen=10)
print(d)

#добавлять элементы можно слева или справа:
d.append(10)
print(d)
d.appendleft(-7)
print(d)
#удалить элементы слева и справа
print(d.pop(),d.popleft())
print(d.pop(),d.popleft())
print(d)
# добавление групп элементов по типу extand
d.extend([11,22,33])
d.extendleft([10,20,30])
print(d)

#развезнуть
d.reverse()
print(d)
#перемещение элементов в начало/конец очереди
d.rotate(3)
print(d)
d.rotate(-6)
print(d)

deque([0, 1, 2, 3, 4, 5], maxlen=10)
deque([0, 1, 2, 3, 4, 5, 10], maxlen=10)
deque([-7, 0, 1, 2, 3, 4, 5, 10], maxlen=10)
10 -7
5 0
deque([1, 2, 3, 4], maxlen=10)
deque([30, 20, 10, 1, 2, 3, 4, 11, 22, 33], maxlen=10)
deque([33, 22, 11, 4, 3, 2, 1, 10, 20, 30], maxlen=10)
deque([10, 20, 30, 33, 22, 11, 4, 3, 2, 1], maxlen=10)
deque([4, 3, 2, 1, 10, 20, 30, 33, 22, 11], maxlen=10)


In [ ]:
# defaultdict - словарь в котором новый ключ содержит объект по-умолчанию
from collections import defaultdict

d = defaultdict(list)
d['1'] = [11,22,33]
print(d['2']) #создасться пустой список
print(d)

[]
defaultdict(<class 'list'>, {'1': [11, 22, 33], '2': []})


In [ ]:
# Счетчик counter
from collections import Counter
c1 = Counter([1,3,2,2,1,3,4,3,2,2,1,1,1,2,4,3])
print(c1)
c2 = Counter([1,1,2,2,3,3,4,4,4,4,5,5,5,5])
print(c2)

#счетчики складываются
print(c1+c2)
#счетчики вычитаются
print(c1-c2) #но значения обнуляются если <=0
c1.subtract(c2)
print(c1) # отнимает с минусами

print(c2.most_common(3)) #3 наиболее частных значения вывести


Counter({1: 5, 2: 5, 3: 4, 4: 2})
Counter({4: 4, 5: 4, 1: 2, 2: 2, 3: 2})
Counter({1: 7, 2: 7, 3: 6, 4: 6, 5: 4})
Counter({1: 3, 2: 3, 3: 2})
Counter({1: 3, 2: 3, 3: 2, 4: -2, 5: -4})
[(4, 4), (5, 4), (1, 2)]


In [ ]:
import numpy as np

#Типы данных
a = np.int16(4) #целые
print(a)
print(np.iinfo(a))

b = np.float64(567.987) #с точкой
print(b)
print(np.finfo(b))

с = np.uint8(56) #натуральные
print(с)
print(np.iinfo(с))

4
Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

567.987
Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
smallest_normal = 2.2250738585072014e-308   smallest_subnormal = 4.9406564584124654e-324
---------------------------------------------------------------

56
Machine parameters for uint8
---------------------------------------------------------------
min = 0
max = 255
---------------------------------------------------------------



In [ ]:
# векторы

from pickletools import float8


v = np.array([1,2,3])
u = np.array([4,-8,1])
print(v+u)
print(v-u)
print(v*u) #поэлементное умножение
print(v*3) #умножение на скаляр
v1 = np.arange(1,10,2, dtype=np.int8) #точно как range, только вектор
print(v1)
print(type(v1))
u1 = np.linspace(1,10,12) #от до и cколько
print(u1)

print(np.linalg.norm(v)) #норма/длина
print(np.linalg.norm(v-u)) #расстояние
print(np.dot(u,v)) #скалярное произведение

u.sort() #сортировка
print(u)

print(f'min {np.min(u)}')
print(f'max {np.max(u)}')
print(f'mean {np.mean(u)}')
print(f'sum {np.sum(u)}')
print(f'median {np.median(u)}')
print(f'std {np.std(u)}')


[ 5 -6  4]
[-3 10  2]
[  4 -16   3]
[3 6 9]
[1 3 5 7 9]
<class 'numpy.ndarray'>
[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]
3.7416573867739413
10.63014581273465
-9
[-8  1  4]
min -8
max 4
mean -1.0
sum -3
median 1.0
std 5.0990195135927845


In [ ]:
matrix = np.array([[1,2,3],
                  [2,3,4],
                  [0,3,6]], dtype=np.int8)
print(matrix[1,1])

print(np.zeros(5)) #создать нулевой вектор
arr = np.zeros((5,4), dtype=np.int8) #создать массив/матрицу
print(arr)
print(arr.shape)
arrT = arr.transpose() #транспонировать
print(arrT)



3
[0. 0. 0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(5, 4)
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# случайные числа

#np.random.seed(34567)

#случайные float от 0 до 1
r = np.random.rand()
print(r, '\n')
r = np.random.rand(5)
print(r,'\n')
r = np.random.rand(3,6)
print(r,'\n')
r = np.random.sample((2,2)) # ~rand, только подаем кортеж
print(r,'\n')

# float из диапазона
r = np.random.uniform(1,100,size=(3,3))
print(r,'\n')

# int из диапазона
r = np.random.randint(1,100,size=(3,3))
print(r,'\n')

#shuffle - перемешать
np.random.shuffle(r)
print(r,'\n')

#permutation - получить перемешанный не меняя исходный
r1 = np.random.permutation(r)
print(r1, '\n')

#choice - случайный выбор с повторами и без
r2 = np.random.choice(np.arange(1,10), [3,3], replace=False) #без повторов
print(r2, '\n')
r2 = np.random.choice(np.arange(1,10), [3,3], replace=True) #с повторами
print(r2, '\n')

0.14567975663243404 

[0.37134616 0.61368171 0.52162943 0.95200145 0.66871663] 

[[0.88231144 0.78163607 0.12242812 0.40451954 0.50527055 0.03023957]
 [0.9862875  0.65252033 0.49077109 0.4154397  0.48429929 0.16352251]
 [0.03269759 0.40179654 0.74766105 0.20889711 0.40345594 0.34752832]] 

[[0.04906066 0.83110138]
 [0.03204295 0.46126495]] 

[[45.84090509 79.41424237 35.51400197]
 [25.69571009  3.25249323 17.91203859]
 [64.9326736  42.38560428 50.39502806]] 

[[29 59 35]
 [12 71 81]
 [ 2 38 72]] 

[[12 71 81]
 [29 59 35]
 [ 2 38 72]] 

[[ 2 38 72]
 [29 59 35]
 [12 71 81]] 

[[8 1 5]
 [7 9 4]
 [3 2 6]] 

[[3 8 5]
 [2 1 5]
 [1 2 8]] 

